//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataController
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CamozziEntities : DbContext
    {
        public CamozziEntities()
            : base("name=CamozziEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AccountDb> AccountDbs { get; set; }
        public DbSet<DeptDb> DeptDbs { get; set; }
        public DbSet<ProjectDb> ProjectDbs { get; set; }
        public DbSet<UserDb> UserDbs { get; set; }
    }
}
