//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataController
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectDb
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime Finish { get; set; }
        public int UserId { get; set; }
        public int ManagerId { get; set; }
        public int CreatorId { get; set; }
        public int State { get; set; }
        public int Priority { get; set; }
        public string Comment { get; set; }
        public int DeptId { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual DeptDb Dept { get; set; }
        public virtual UserDb Creator { get; set; }
        public virtual UserDb Manager { get; set; }
        public virtual UserDb Worker { get; set; }
    }
}
