//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataController
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDb
    {
        public UserDb()
        {
            this.ProjectDbs = new HashSet<ProjectDb>();
            this.ProjectDbs1 = new HashSet<ProjectDb>();
            this.ProjectDbs2 = new HashSet<ProjectDb>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public int DeptId { get; set; }
        public string Password { get; set; }
        public string Mail { get; set; }
        public int AccountId { get; set; }
        public string Comment { get; set; }
        public int QueryId { get; set; }
    
        public virtual AccountDb AccountDb { get; set; }
        public virtual DeptDb DeptDb { get; set; }
        public virtual ICollection<ProjectDb> ProjectDbs { get; set; }
        public virtual ICollection<ProjectDb> ProjectDbs1 { get; set; }
        public virtual ICollection<ProjectDb> ProjectDbs2 { get; set; }
    }
}
