//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataController
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDb
    {
        public UserDb()
        {
            this.CreatedProjects = new HashSet<ProjectDb>();
            this.ManagedProjects = new HashSet<ProjectDb>();
            this.WorkedProjects = new HashSet<ProjectDb>();
            this.CreatedReclamations = new HashSet<ReclamationDb>();
            this.ManagedReclamations = new HashSet<ReclamationDb>();
            this.WorkedReclamation = new HashSet<ReclamationDb>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public int DeptId { get; set; }
        public string Password { get; set; }
        public string Mail { get; set; }
        public int AccountId { get; set; }
        public string Comment { get; set; }
    
        public virtual AccountDb Account { get; set; }
        public virtual DeptDb Dept { get; set; }
        public virtual ICollection<ProjectDb> CreatedProjects { get; set; }
        public virtual ICollection<ProjectDb> ManagedProjects { get; set; }
        public virtual ICollection<ProjectDb> WorkedProjects { get; set; }
        public virtual ICollection<ReclamationDb> CreatedReclamations { get; set; }
        public virtual ICollection<ReclamationDb> ManagedReclamations { get; set; }
        public virtual ICollection<ReclamationDb> WorkedReclamation { get; set; }
    }
}
