//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Projects = new HashSet<Project>();
            this.Projects1 = new HashSet<Project>();
            this.Projects2 = new HashSet<Project>();
            this.Reclamations = new HashSet<Reclamation>();
            this.Reclamations1 = new HashSet<Reclamation>();
            this.Reclamations2 = new HashSet<Reclamation>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public int DeptId { get; set; }
        public string Password { get; set; }
        public string Mail { get; set; }
        public int AccountId { get; set; }
        public string Comment { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Dept Dept { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<Project> Projects1 { get; set; }
        public virtual ICollection<Project> Projects2 { get; set; }
        public virtual ICollection<Reclamation> Reclamations { get; set; }
        public virtual ICollection<Reclamation> Reclamations1 { get; set; }
        public virtual ICollection<Reclamation> Reclamations2 { get; set; }
    }
}
